# Generated by Django 3.1.7 on 2021-04-10 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestboardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardName', models.CharField(max_length=100, null=True, verbose_name='Board Name')),
                ('boardDescription', models.CharField(max_length=100, null=True, verbose_name='Board Description')),
                ('numStars', models.IntegerField(default=0, verbose_name='Number of Stars')),
            ],
        ),
        migrations.CreateModel(
            name='QuestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questName', models.CharField(max_length=100, null=True, verbose_name='Quest Name')),
                ('numStars', models.IntegerField(default=0, verbose_name='Number of Stars')),
                ('forAll', models.BooleanField(default=True, verbose_name='For all students')),
                ('boardOrigin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questboard.questboardmodel', verbose_name='Board Name')),
            ],
        ),
    ]
