# Generated by Django 3.1.7 on 2021-04-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0003_auto_20210410_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='questmodel',
            name='student1',
            field=models.CharField(default='', max_length=99, verbose_name='student 1'),
        ),
        migrations.AddField(
            model_name='questmodel',
            name='student2',
            field=models.CharField(default='', max_length=99, verbose_name='student 2'),
        ),
        migrations.AddField(
            model_name='questmodel',
            name='student3',
            field=models.CharField(default='', max_length=99, verbose_name='student 3'),
        ),
    ]
