# Generated by Django 3.1.7 on 2021-04-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0004_auto_20210410_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questmodel',
            name='student1',
            field=models.CharField(blank='True', default='', max_length=99, verbose_name='student 1'),
        ),
        migrations.AlterField(
            model_name='questmodel',
            name='student2',
            field=models.CharField(blank='True', default='', max_length=99, verbose_name='student 2'),
        ),
        migrations.AlterField(
            model_name='questmodel',
            name='student3',
            field=models.CharField(blank='True', default='', max_length=99, verbose_name='student 3'),
        ),
    ]
